# FFNx config file

### HOW TO: ###################################################################
# Options may be commented by default with an initial # character.
# Remove the initial # character to set the configuration flag.
# -----------------------------------------------------------------------------
# Unless options are specified, you can either disable or enable a flag.
# Enable: true
# Disable: false
###############################################################################

# =============================================================================

###############################################################################
# COMMON OPTIONS FOR BOTH FF7 AND FF8
###############################################################################

#########################
## DISPLAY
#########################

#[RENDERING BACKEND]
# Available choices are:
# - 0: Auto ( default, will pick the best rendering backend for your GPU )
# - 1: OpenGL ( works fine on Intel/Nvidia, MAY break on AMD )
# - 2: Direct3D9 ( Tech Preview: Not Recommended )
# - 3: Direct3D11 ( works fine under any GPU on Windows )
# - 4: Direct3D12
# - 5: Vulkan
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#renderer_backend = 0

#[FULLSCREEN]
# If off, it will run in window mode.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#fullscreen = false

#[RESOLUTION]
# Resolution of the game.
# Default (value = 0):
# - Window mode will use 640x480
# - Fullscreen mode will use your desktop resolution
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#window_size_x = 0
#window_size_y = 0

#[INTERNAL RESOLUTION SCALE]
# The scale is in multiples of 640x480
# The scale factor is used to render internally at a larger size then the display, this will then be downscaled to the games current resolution
# This is required to avoid visual glitches that may happen when the game is not rendered in a 4:3 aspect ratio.
# This is optional for native 4:3 resolutions, but it will enhance visual quality ( like Nvidia DSR ).
# Default = 2
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#internal_resolution_scale = 2

#[PRESERVE ASPECT]
# Preserve original game aspect ratio of (4:3) by adding black bars on the left and right side (if needed)
# When off the game will be stretched to fit the window's aspect ratio; Be aware the game may look wrong though.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#preserve_aspect = true

#[ENABLE VSYNC]
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_vsync = true


#[REFRESH RATE]
# Screen refresh rate.
# Default is 0 = use current screen refresh rate
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#refresh_rate = 0

#[LINEAR FILTERING]
# Allow the usage of linear filtering for textures.
# Please note: some things look slightly better with this option on, but alot of textures just lose their detail.
# This option only affects low-res textures, high-res replacements will still be filtered where appropriate.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#linear_filter = false

#[ANTIALIASING]
# Enable antialiasing filtering, this is done in the last pass when downsampling from the current supersampled rendering ( based on internal_resolution_scale logic )
# Available choices are:
# - 0: Disabled ( Default )
# - 2: 2x
# - 4: 4x
# - 8: 8x
# - 16: 16x
# If you set any value that is different than those, it will pick the higher option ( eg. if you pick 6 it will be 8, if you pick 1 it will be 2, and so on ).
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_antialiasing = 0

#[ANISOTROPIC]
# Enable anisotropic filtering, for high-res textures and overall rendering
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_anisotropic = true

#########################
# Audio Player Options
#########################

#[USE EXTERNAL SFX]
# This flag will enable/disable the support of an enhanced audio layer to reproduce sounds in-game.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#use_external_sfx = false

#[EXTERNAL SFX PATH]
# Path of the external sound files
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#external_sfx_path = "sfx"

#[EXTERNAL SFX EXTENSION]
# The type of file to search for. By default is ogg.
# Supported extensions:
# - ogg, mp3, flac, wav
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#external_sfx_ext = "ogg"

#[USE EXTERNAL MUSIC]
# This flag will enable/disable the support of an enhanced audio layer to reproduce music in-game.
# If you leave out the default configuration FFNx will autodetect your environment and will set it to the best available option.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#use_external_music = false

#[EXTERNAL MUSIC RESUME]
# This flag will enable the support for music resume on known areas of the game ( for eg. World-Map ).
# If you enable this flag, instead of starting the OST for a known area from the beginning everytime, it will resume where you left it off the last time you visited it.
#external_music_resume = true

#[EXTERNAL MUSIC PATH]
# Path of the external music files
# Will try to load from this path before using the default for your Version of the game
# Defaults:
# - FF7 1998: music/vgmstream ( 7h-era compatibility )
# - FF7 eStore: data/music_ogg
# - FF7 Steam: data/music_ogg
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#external_music_path = ""

#[EXTERNAL MUSIC EXTENSION]
# The type of file to search for. By default is ogg.
# Supported extensions:
# - https://github.com/losnoco/vgmstream#supported-file-types
# - psf, psf2, minipsf, minipsf2 (PSF and PSF2) if you provide the Highly Experimental BIOS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#external_music_ext = "ogg"

#[EXTERNAL MUSIC HIGHLY EXPERIMENTAL BIOS]
# This flag will enable support to PSF and PSF2 formats.
# You need to provide a BIOS generated for the Highly Experimental project (hebios.bin).
# To find one compiled BIOS: https://git.lopez-snowhill.net/chris/foo_psf
# To generate one: https://git.lopez-snowhill.net/chris/highly_experimental
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#he_bios_path = ""

#[EXTERNAL VOICE PATH]
# Path of the external voice files
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#external_voice_path = "voice"

#[EXTERNAL VOICE EXTENSION]
# The type of file to search for. By default is ogg.
# Supported extensions:
# - ogg, mp3, flac, wav
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#external_voice_ext = "ogg"

#[ENABLE VOICE MUSIC FADE]
# This flag will enable the music volume fade out and fade in, when a voice acting is being played back.
# Please note this flag will take effect ONLY when "use_external_music" is enabled.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_voice_music_fade = false

#[EXTERNAL VOICE MUSIC FADE VOLUME]
# This flag will set to how much the volume will be lowered down when a voice acting is going to be played back. When the voice file will be finished, the music volume will be then restored to its previous value.
# Range: 0-100 ( Min = 0, Max = 100)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#external_voice_music_fade_volume = 25

###########################
# Video Player Options
###########################

#[ENABLE FFMPEG VIDEOS]
# This flag will enable/disable the support of FFMpeg layer to reproduce movies in-game.
# Default Value depends on game version.
# - FF7 1998 - true
# - FF7/FF8 Steam - true
# - FF8 2000 - false
# It is suggested to keep the default behavior unless you really know what are you doing.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_ffmpeg_videos = true

#[FFMPEG VIDEO FILE EXTENSION]
# The type of file that the ffmpeg layer will search for. Default is avi.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ffmpeg_video_ext = "avi"

###############################
# MUST SET FOR VERSIONS BELOW
# FF7 2012   FF7 STEAM
# FF8 2013   FF8 STEAM
###############################
# The folder name in your game Documents path ( for eg. for FF7 is "C:\Users\JohnDoe\Documents\Square Enix\FINAL FANTASY VII Steam\user_XXXXXXX")
# Use this only if you have MORE THAN ONE user_* directories. If not, just leave this commented as the driver will autodetect the directory.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#steam_game_userdata = "user_12345678"

########################
## MODDER OPTIONS
########################

#[TEXTURE PATH]
# Mod directory where textures will be loaded from
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#mod_path = "mods/Textures"

# Show every failed attempt at loading a .png or .dds texture
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_missing_textures = false

# Dump internal textures to PNG files in the mod_path
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#save_textures = false

# This path is where the Hext patching layer will look for txt files.
# The path will ALWAYS have appended:
# 1. The game name ( if FF7 it will be "ff7/", if FF8 will be "ff8/")
# 2. The game language ( for eg. if ff7_en it will be "en" )
# The resulting path will then be "<hext_patching_path>/ff7/en", if you run for eg. FF7 English
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#hext_patching_path = "hext"

# This path will define where the driver will look first, allowing you to override core game files, if needed
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#override_path = "override"

#[SPEEDHACK]
# Set the step when increasing the speedhack speed
#~~~~~~~~~~~~~~~~~~~~~~~~~~
#speedhack_step = 0.5

# Set the limit of the speedhack multiplier
#~~~~~~~~~~~~~~~~~~~~~~~~~~
#speedhack_max = 8.0
#speedhack_min = 1.0

#[EXPERIMENTAL]
# Enable support for animated textures.
# WARNING: This flag MAY degrade the gameplay performance. Enable at your own risk.
#~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_animated_textures = false

##########################
# DEBUGGING OPTIONS
# These options are mostly useful for developers or people reporting crashes.
# Please do enable them only when required.
##########################

# Enable FFNx DevTools
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_devtools = false

# Set hotkey to toggle the DevTools window.
# This is specified by a virtual-key code hexadecimal value, see: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Default: 0x7B ( VK_F12 )
#devtools_hotkey = 0x7B

# Display the verion of FFNx in upper right corner ( when fullscreen ) or in the title bar ( when windowed )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_version = true

# Display frames per second counter in upper right corner ( when fullscreen ) or in the title bar ( when windowed )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_fps = false

# Display Rendering backend in upper right corner ( when fullscreen ) or in the title bar ( when windowed )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_renderer_backend = true

# Display some real-time debug information
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_stats = false

# Enable logging
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_applog = true

# Show on screen error messages ( only on fullscreen )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_error_popup = false

# Enable this flag if you want to see more verbose output from the backend renderer.
# Usually useful for debug pruposes. Do not enable otherwise.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#renderer_debug = false

# Creates a full crashdump file if the game crashes. Useful to be analyzed with WinDbg when reporting issues.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#create_crash_dump = false

# Various flags which will help in further debugging the game engine logics.
# Some flags may not generate any output depending on the game you play.

# trace_all - Dump in the logs whatever APIs is being called from the Engine in FFNx. Overrides all the others below.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_all = false

# trace_renderer - Dump in the logs only APIs that has to do with the rendering engine
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_renderer = false

# trace_movies - Dump in the logs only APIs that has to do with movie playback
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_movies = false

# trace_music - Dump in the logs only APIs that has to do with music playback
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_music = false

# trace_sfx - Dump in the logs only APIs that has to do with sfx playback
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_sfx = false

# trace_fake_dx - Dump in the logs only APIs that has to do with directdraw emulation
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_fake_dx = false

# trace_direct - Dump in the logs only APIs that has to do with LGP loading
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_direct = false

# trace_files - Dump in the logs only APIs that has to do with filesystem operations
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_files = false

# trace_loaders - Dump in the logs only APIs that has to do with internal textures overrides
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_loaders = false

# trace_opcodes - Dump in the logs only APIs that has to do with field opcodes
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_opcodes = false

# trace_voice - Dump in the logs only APIs that has to do with voice playback
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_voice = false

# vertex_log - Dump in the logs current engine vertex data being passed to the GPU for drawing
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#vertex_log = false

# uniform_log - Dump in the logs current engine uniform data being passed to the GPU shaders
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#uniform_log = false

# Show debug info regarding movie synchronization.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#movie_sync_debug = false

###############################################################################
# OPTIONS ONLY FOR FF7
###############################################################################

## ENHANCEMENTS

# Include armor in magic defense calculation
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#mdef_fix = true

## ADVANCED OPTIONS - Don't fiddle with these unless you know what you're doing.

# Skip movie frames if necessary.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#skip_frames = false

## MODDER OPTIONS - These options are mostly useful to modders and should not be enabled during normal play.

# This is the path where files where be read directly, instead then reading them inside the LGP archives.
# For example: if FF7 is looking for aaab.rsd in char.lgp, this option will make it open direct/char/aaab.rsd first,
# If this file doesn't exist it will look for the original in the LGP archive
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#direct_mode_path = "direct"

# This is the path where your savefiles will be read.
# Notice that the path will be relative to your FF7 Game install directory, where usually the "save" directory is stored.
# PLEASE NOTE: THIS IS A VALID OPTION ONLY FOR FF7 1998/eStore edition. It will NOT work on the Steam edition!
#save_path = "save"

## DEBUGGING OPTIONS - These options are mostly useful for developers or people reporting crashes. Please do enable them only when required.

# Dump in the logs more verbose error messages coming directly from the engine
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ff7_more_debug = false

###############################################################################
# OPTIONS ONLY FOR FF8
###############################################################################

## ENHANCEMENTS

# FF8 by default is used to pause the game when the window has false focus. This flag will override this behavior and will allow you to NOT pause the game and keep it running, if set to true.
# This flag may be useful for streamers which may not want the game to be paused while switching the focus on another window.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ff8_keep_game_running_in_background = false

## DEBUGGING OPTIONS - These options are mostly useful for developers or people reporting crashes. Please do enable them only when required.

# Show the PSX SSIGPU VRAM window
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ff8_ssigpu_debug = false
