# FFNx Lighting config file

### HOW TO: ###################################################################
# Sections may be commented by default with an initial # character.
# Remove the initial # character to set the entire sections block and its flags
# -----------------------------------------------------------------------------
###############################################################################

### SUPPORTED FLAGS: ##########################################################
# disable_lighting_textures : disables lighting for models using the given
# texture names
###############################################################################

light_rotation_vertical = 60.0
light_rotation_horizontal = 60.0
light_intensity = 4.0
light_color = [ 1.0, 1.0, 1.0 ]
ambient_light_intensity = 1.0
ambient_light_color = [ 1.0, 1.0, 1.0 ]
material_roughness = 0.7
material_metallic = 0.5
material_specular = 0.2

disable_lighting_textures = [
  "STAGE01_T05", "STAGE02_T01", "STAGE02_T02", "STAGE03_T01", "STAGE04_T01",
  "STAGE05_T01", "STAGE05_T02", "STAGE06_T01", "STAGE06_T02", "STAGE07_T01",
  "STAGE07_T02", "STAGE08_T01", "STAGE08_T02", "STAGE19_T01", "STAGE19_T02",
  "STAGE19_T03", "STAGE20_T01", "STAGE20_T02", "STAGE23_T01", "STAGE23_T02",
  "STAGE33_T01", "STAGE33_T02", "STAGE34_T01", "STAGE34_T02", "STAGE36_T01",
  "STAGE36_T02", "STAGE38_T01", "STAGE39_T01", "STAGE40_T02", "STAGE40_T03",
  "STAGE44_T01", "STAGE47_T01", "STAGE47_T02", "STAGE53_T01", "STAGE58_T01",
  "STAGE58_T02", "STAGE59_T01", "STAGE61_T01", "STAGE61_T02", "STAGE62_T01",
  "STAGE62_T02", "STAGE63_T01", "STAGE63_T02", "STAGE64_T01", "STAGE64_T02",
  "STAGE65_T01", "STAGE66_T01", "STAGE66_T02", "STAGE67_T01", "STAGE67_T02",
  "STAGE68_T06", "STAGE69_T04", "STAGE70_T01", "STAGE70_T02", "STAGE71_T01",
  "STAGE71_T02", "STAGE72_T01", "STAGE72_T02", "STAGE79_T01", "STAGE80_T01",
  "STAGE80_T02", "STAGE81_T01", "STAGE81_T02", "STAGE84_T01", "STAGE84_T02",
  "STAGE84_T03", "STAGE87_T01", "STAGE87_T02", "STAGE88_T01", "STAGE88_T02",
  "STAGE89_T01"
]

[field_ancnt1]
shadowmap_fade_start_distance = 200.0

[field_anfrst_3]
shadowmap_fade_start_distance = 200.0

[field_blin66_5]
shadowmap_fade_start_distance = 200.0

[field_blin68_1]
shadowmap_fade_start_distance = 100.0

[field_blinst_1]
shadowmap_fade_start_distance = 200.0

[field_blinst_2]
shadowmap_fade_start_distance = 200.0

[field_blinst_3]
shadowmap_fade_start_distance = 200.0

[field_blue_1]
shadowmap_area = 6000.0

[field_convil_1]
shadowmap_fade_start_distance = 200.0

[field_cos_btm]
shadowmap_fade_start_distance = 200.0

[field_cos_top]
shadowmap_fade_start_distance = 200.0

[field_del1]
shadowmap_area = 3500.0

[field_del12]
shadowmap_area = 3500.0

[field_del2]
shadowmap_fade_start_distance = 100.0

[field_fship_4]
shadowmap_fade_start_distance = 200.0

[field_fship_42]
shadowmap_fade_start_distance = 200.0

[field_gaia_2]
shadowmap_fade_start_distance = 200.0

[field_gaiafoot]
shadowmap_area = 3500.0

[field_gaiin_1]
shadowmap_fade_range = 100.0
shadowmap_fade_start_distance = 100.0

[field_gnmkf]
shadowmap_area = 3800.0

[field_holu_2]
shadowmap_fade_start_distance = 100.0

[field_junair]
shadowmap_area = 3600.0

[field_junonr1]
shadowmap_area = 4000.0

[field_las0_1]
shadowmap_fade_start_distance = 200.0

[field_las1_2]
shadowmap_fade_start_distance = 200.0

[field_losin1]
shadowmap_fade_start_distance = 100.0

[field_losin2]
shadowmap_fade_start_distance = 200.0

[field_losin3]
shadowmap_fade_start_distance = 100.0

[field_loslake1]
shadowmap_fade_start_distance = 200.0

[field_lost1]
shadowmap_area = 3100.0

[field_md8_32]
shadowmap_fade_start_distance = 200.0

[field_md8_b1]
shadowmap_fade_start_distance = 200.0

[field_md8_b2]
shadowmap_fade_start_distance = 200.0

[field_mds7st32]
shadowmap_area = 3500.0

[field_mtcrl_3]
shadowmap_fade_start_distance = 200.0

[field_mtcrl_9]
shadowmap_area = 5100.0

[field_rcktbas1]
shadowmap_fade_start_distance = 200.0

[field_sandun_1]
shadowmap_fade_start_distance = 200.0

[field_sango1]
shadowmap_fade_start_distance = 100.0

[field_sango2]
shadowmap_area = 6000.0

[field_sango3]
shadowmap_fade_start_distance = 200.0

[field_shpin_2]
shadowmap_fade_start_distance = 200.0

[field_shpin_22]
shadowmap_fade_start_distance = 200.0

[field_sinin3]
shadowmap_fade_start_distance = 200.0

[field_trnad_3]
shadowmap_area = 3750.0